version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - license-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: licensedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - license-network

volumes:
  postgres_data:

networks:
  license-network:
    driver: bridge